create extension if not exists pgcrypto;

create table if not exists public.rounds (
  id uuid primary key default gen_random_uuid(),
  share_id text not null unique,
  edit_token_hash text not null,
  course_source text not null check (course_source in ('opengolfapi', 'manual')),
  external_course_id text,
  course_name text not null,
  course_layout_name text,
  city text,
  state text,
  tee_name text,
  source_license text not null default 'ODbL-1.0',
  round_type text not null check (round_type in ('front_9', 'back_9', 'nine_hole_course', 'full_18')),
  played_at date not null,
  total_score smallint not null,
  total_par smallint not null,
  score_to_par smallint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rounds_course_name_length check (char_length(course_name) between 1 and 180),
  constraint rounds_share_id_format check (share_id ~ '^[A-Z2-9]{7}$')
);

create table if not exists public.round_holes (
  id bigint generated by default as identity primary key,
  round_id uuid not null references public.rounds(id) on delete cascade,
  display_order smallint not null check (display_order between 1 and 18),
  course_hole_number smallint not null check (course_hole_number between 1 and 18),
  par smallint not null check (par between 2 and 7),
  score smallint not null check (score between 1 and 20),
  result_category text not null check (result_category in ('eagle_or_better', 'birdie', 'par', 'bogey', 'double_or_worse')),
  unique (round_id, display_order)
);

create index if not exists rounds_created_at_idx on public.rounds (created_at desc);
create index if not exists round_holes_round_id_idx on public.round_holes (round_id, display_order);

alter table public.rounds enable row level security;
alter table public.round_holes enable row level security;

-- The app performs anonymous create, read, and edit operations only from its
-- server routes using the service-role key. No browser-facing table policy is
-- needed, so edit tokens never leave the server API boundary.
